name: Push JSON to Lokalise

on:
  workflow_dispatch:
  push:
    paths:
      - github_action/en.json
    branches:
      - main 

jobs:
  push-to-lokalise:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # Navigate to the directory containing package.json and install dependencies
      - name: Install dependencies
        run: |
          cd giacven/github_action  # Change to the directory containing package.json
          npm install

      # Debug Environment Variables
      - name: Debug Environment Variables
        run: |
          echo "LOKALISE_PROJECT_ID is set."

      # Push the updated file to Lokalise
      - name: Push JSON file to Lokalise
        env:
          LOKALISE_API_TOKEN: ${{ secrets.LOKALISE_API_TOKEN }}
          LOKALISE_PROJECT_ID: ${{ secrets.LOKALISE_PROJECT_ID }}
        run: |
          curl -X POST "https://api.lokalise.com/api2/projects/$LOKALISE_PROJECT_ID/files/upload" \
          -H "X-Api-Token: $LOKALISE_API_TOKEN" \
          -F "file=@ggithub_action/en.json" \
          -F "data={\"convert_placeholders\": false, \"replace_modified\": true, \"tags\": [\"auto-updated\"]}" || { echo "Curl command failed"; exit 1; }

