name: Push JSON to Lokalise

on:
  workflow_dispatch:
  push:
    paths:
      - github_action/en.json  # Trigger when this file is updated
    branches:
      - main  # Only trigger on changes to the main branch

jobs:
  push-to-lokalise:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch full history to ensure all file details are available

      # Push the JSON file to Lokalise
      - name: Push JSON file to Lokalise
        run: |
          curl -v -X POST "https://api.lokalise.com/api2/projects/8924818166f90cfed9af35.66887635/files/upload" \
          -H "X-Api-Token: 919873230a09f13d63d67ab49874325072977cf9" \
          -F "file=@github_action/en.json"
