name: PushtoTMS

on:
  workflow_dispatch:  
  push:
    paths:
      - en.json  
    branches:
      - main 

jobs:
  push-to-lokalise:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  

     
      - name: PushtoTMS
        env:
          LOKALISE_API_TOKEN: ${{ secrets.LOKALISE_API_TOKEN }}  
          LOKALISE_PROJECT_ID: ${{ secrets.LOKALISE_PROJECT_ID }}  
        run: |
          curl -X POST "https://api.lokalise.com/api2/projects/8924818166f90cfed9af35.66887635/files/upload" \
          -H "X-Api-Token: 919873230a09f13d63d67ab49874325072977cf9" \
          -F "file=@en.json" \
          -F "data={\"convert_placeholders\": false, \"replace_modified\": true, \"tags\": [\"auto-updated\"]}"

