name: Push JSON to Lokalise

on:
  workflow_dispatch:
  push:
    paths:
      - en.json  # Trigger when this file is updated
    branches:
      - main  # Only trigger on changes to the main branch

jobs:
  push-to-lokalise:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Push JSON file to Lokalise
        run: |
          curl -v -X POST "https://api.lokalise.com/api2/projects/${{ secrets.LOKALISE_PROJECT_ID }}/files/upload" \
             -H "X-Api-Token: ${{ secrets.LOKALISE_API_TOKEN }}" \
             -F "file=@en.json" \
             -F 'data={\"convert_placeholders\": false, \"replace_modified\": true, \"tags\": [\"auto-updated\"]}'
          if [[ $? -ne 0 ]]; then
            echo "Error: Failed to upload en.json to Lokalise!"
            exit 1
          fi
          echo "Successfully uploaded en.json to Lokalise!"
