name: Push JSON to Lokalise

on:
  workflow_dispatch:
  push:
    paths:
      - en.json  # Trigger when this file is updated
    branches:
      - main  # Only trigger on changes to the main branch

jobs:
  push-to-lokalise:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Push JSON file to Lokalise
        run: |
          curl -v -X POST "https://api.lokalise.com/api2/projects/8924818166f90cfed9af35.66887635/files/upload" \
             -H "X-Api-Token: 919873230a09f13d63d67ab49874325072977cf9" \
             -F "file=@${file}" \
             -F 'data={\"convert_placeholders\": false, \"replace_modified\": true, \"tags\": [\"auto-updated\"]}'
          if [[ $? -ne 0 ]]; then
            echo "Error: Failed to upload en.json to Lokalise!"
            exit 1
          fi
          echo "Successfully uploaded en.json to Lokalise!"
